### ISSUE TITLE
Parameter value [true] did not match expected type [java.lang.Boolean (n/a)]; nested exception is java.lang.IllegalArgumentException: Parameter value [true] did not match expected type [java.lang.Boolean (n/a)]

### ISSUE THREAD

**Issue by nivekalara237** [sipios/spring-search#12]
I can not do a query on a Boolean type.
here is my model
`

import ...
@Getter(AccessLevel.PUBLIC)
@Setter(AccessLevel.PUBLIC)
@ToString
@Entity
@Table(name = "plan_travail")
public class PlanTravail extends Auditable implements Serializable {
    @Id
    private Long id;
    @Column(name = "entreprise_id")
    private Long entrepriseId;
    @Column(name = "fuseau_horaire", columnDefinition = "varchar(64) default 'Africa/Douala'")
    private String fuseauHoraire;
    @Column(name = "par_defaut")
    private boolean parDefaut;
}
`
and here is the query in question:
http://localhost:8097/api/search/planTravails?search=parDefaut:true

**Comment by luc-boussant** [comment]
We just merge a [pull request](https://github.com/sipios/spring-search/pull/10) that implements this feature
