### ISSUE TITLE
Allow for searching lists

### ISSUE THREAD

**Issue by redhawk87** [sipios/spring-search#13]
With the current implementation, I do not see a way to filter results based on if a list contains an item, or does not contain an item.  For example, OData has 'any' and 'all' keywords that allow you to search lists.

**Comment by luc-boussant** [comment]
Can you please provide a concrete example of what you would want to be possible with the spring search annotation ?
It will help us narrow the feature that you would want to be added

**Comment by luc-boussant** [comment]
I will close this issue for now until the feature is a bit clearer.
