### ISSUE TITLE
Add ignore case equality for strings

### ISSUE THREAD

**Issue by mhsnrmz** [sipios/spring-search#16]
I think it would be great if you can add case insensitive search for strings.

**Comment by luc-boussant** [comment]
This feature has been implemented in the linked PR

**Comment by segtio** [comment]
Hello this feature should be on the 0.2.1 version from maven artifact but it wasn't . Is that normal since it belongs to the same tag on github ?

**Comment by luc-boussant** [comment]
Hello, indeed we are having a problem with the publishment of the 0.2.1 version.

**Comment by luc-boussant** [comment]
Hello, a new release has now been published and tagged as 0.2.2.
The ignore case equality was added to this maven artifacts. 
Thanks for waiting ;)
