### ISSUE TITLE
Search on Enumerated type Filed

### ISSUE THREAD

**Issue by ricklimon** [sipios/spring-search#21]
Be able to search on javax.persistence.Enumerated(EnumType.STRING) fields.

Currently throws 
java.lang.IllegalArgumentException: Parameter value [STATUS_1] did not match expected type [my.package.Status (n/a)]

my.package.Status -> enum
STAUTS_1

http://localhost:8080/api/admin/values?search=valueStatus:STATUS_1

**Comment by hr-ireh** [comment]
EnumStrategy 

![image](https://user-images.githubusercontent.com/20404639/107991063-111c5800-6feb-11eb-8c48-59a0ec069e06.png)

![image](https://user-images.githubusercontent.com/20404639/107991120-34df9e00-6feb-11eb-8393-bcc268508a55.png)

**Comment by hr-ireh** [comment]
Hello
I solved the problem this way and also added other types to it, and add Possibility to check for empty and null.

Edit ParsingStrategy:
![image](https://user-images.githubusercontent.com/20404639/107991361-b1727c80-6feb-11eb-9f4b-18f35dd39453.png)

![image](https://user-images.githubusercontent.com/20404639/107991404-ce0eb480-6feb-11eb-894c-46f297de349e.png)

**Comment by luc-boussant** [comment]
https://github.com/sipios/spring-search/pull/32

**Comment by gdtrp** [comment]
Hi! Still having this error on 0.2.4 version  
Parameter value [ECUSNONE] did not match expected type [model.CertificateUsageType (n/a)]

**Comment by gdtrp** [comment]
Hi all! Conducted additional research and found out, that the problem only take place if my application started through mvn spring-boot:run or inside intellij idea. With java -jar app.jar works properly

**Comment by 1sethiGaurav** [comment]
> Hi all! Conducted additional research and found out, that the problem only take place if my application started through mvn spring-boot:run or inside intellij idea. With java -jar app.jar works properly

What the reason for that?  I really want to know the reason . Can you help me out I got the same problem

**Comment by ShishkinDmitriy** [comment]
Hi, it doesn't fork for me too. 

Version 0.2.4. Starting by gradle bootRun
I found the error is in `QueryParameterBindingValidator`.. It checks that enum value is instanceof enum type.
They are the same types, BUT! loaded with different ClassLoader's:

- RestartClassLoader
- Launcher$AppClassLoader

That's why it thinks they are different types.

Best regards,
Dmitry
