### ISSUE TITLE
[Feature] Blocking specific fields

### ISSUE THREAD

**Issue by Skyterix1991** [sipios/spring-search#22]
An annotation like @BlockSearch to block queries like ?search=password_hash:EXAMPLE_HASH

**Comment by luc-boussant** [comment]
Hello,

This is one of the features that will need to be implemented in the future.
It is added to the roadmap of the project : https://trello.com/b/fXRLZM8y/spring-search
However, if you want to work on it you can create an MR with the changes :)
I will be happy to review it when I can.
