### ISSUE TITLE
[Feature] support BETWEEN and NOT BETWEEN  - IN and NOT IN  where clause

### ISSUE THREAD

**Issue by xanana** [sipios/spring-search#23]
[Feature] support BETWEEN and NOT BETWEEN  - IN and NOT IN  where clause

**Comment by luc-boussant** [comment]
Hello,

I added this feature to our current roadmap : https://trello.com/b/fXRLZM8y/spring-search
I will close this issue. If you want to create an MR with this feature, I will be happy to read and approve your MR
