### ISSUE TITLE
Query with nullable values

### ISSUE THREAD

**Issue by jreinaldooo** [sipios/spring-search#30]
Hi, 

I couldn't identify a way to execute a query with values equal to null in database, this is an issue or lack of my knowledge?

Regards

**Comment by luc-boussant** [comment]
Hello, 

You want to query a database with a search parameter that is equal to null or you need to search a parameter that can be null in your database.

**Comment by luc-boussant** [comment]
If you are thinking of searching the rows that have a certain parameter that equals null we do not yet support this feature. 
However, we are not closed to the idea of implementing it in the feature. 
If you want you can submit a pull request and I will be happy to read it as soon as possible. 

For now, I will close the issue. You can reopen it if you want to get started on the MR.
