### ISSUE TITLE
Security problem

### ISSUE THREAD

**Issue by hr-ireh** [sipios/spring-search#39]
The result of the library v0.2.2 review based on OWASP, I am trying to solve it, you have a solution?
https://nvd.nist.gov
![image](https://user-images.githubusercontent.com/20404639/114302762-b6c9e000-9adf-11eb-8938-d992f812c26f.png)

**Comment by luc-boussant** [comment]
Hello @hr-ireh, if you want to try and fix this problem on spring-search, it would be very nice to create an MR. 
Something you can do to check the vulnerabilities is to launch `mvn verify` after cloning the repository. 
It will output an HTML file which will include the vulnerable dependencies that need a bump :)

**Comment by hr-ireh** [comment]
Hello @luc-boussant , I used  OWASP [Dependency-Check](https://plugins.jenkins.io/dependency-check-jenkins-plugin/) in jenkins, Thanks to the solutions :)
