### ISSUE TITLE
Allow Searching by UUID 

### ISSUE THREAD

**Issue by DavidDiaz1949** [sipios/spring-search#40]
Hello!

I would like to be able to find objects by uuid, 
When I try to pass a UUID type in the Specs it says "Parameter value [3fa85f64-5717-4562-b3fc-2c963f66afa6] did not match expected type [java.util.UUID (n/a)]". This considering that my model has JpaRepository<MyModel, UUID>.
As well, there's no way to cast or parse the specs content, so I could just parse it by using UUID.fromString(specs content).

Any idea or assist ? 
Thanks for reading...

**Comment by luc-boussant** [comment]
Hello,
Thank you for taking the time to write this issue. 
A PR was just merged adding this feature to the SpringSearch annotation. 
I will be deploying the new package version by friday.

**Comment by luc-boussant** [comment]
@DavidDiaz1949 Hello sorry for the wait, just released the new version to 0.2.4.

**Comment by DavidDiaz1949** [comment]
Working as expected!!, Thanks a lot Luc.
