### ISSUE TITLE
LocalDateTime is not supported yet

### ISSUE THREAD

**Issue by AndriOstaJappware** [sipios/spring-search#50]
If use LocalDateTime like input parameter it is not working  -"Could not parse input for the field createdOn as a LocalDateTime"

Can you suggest any workaround?

**Comment by hr-ireh** [comment]
![date format](https://user-images.githubusercontent.com/20404639/139645753-aeb923c7-e385-46c0-97e0-e0bf85edfe92.png)

**Comment by adlmez** [comment]
We have not seen any activity on this project for a long time.
Try using https://github.com/commerce-io/spring-boot-starter-data-search

**Comment by infinito84** [comment]
I had the same problem for whom that don't understand the solution it's to use the completed format example:
`
search=localDateTimeAttr>'2022-12-26T10:00:00' AND localDateTimeAttr>'2022-12-26T23:59:59'
`

**Comment by mlz11** [comment]
The feature has been merged with #38 and deployed with [spring-search-0.2.4](https://github.com/sipios/spring-search/releases/tag/spring-search-0.2.4). 

I will then close this issue.
