### ISSUE TITLE
Support For Boolean Type

### ISSUE THREAD

**Issue by premkumarmcse** [sipios/spring-search#54]
Please add support for Boolean type.

```
{
    "message": "Server Error",
    "details": [
        "Parameter value [TRUE] did not match expected type [java.lang.Boolean (n/a)]; nested exception is java.lang.IllegalArgumentException: Parameter value [TRUE] did not match expected type [java.lang.Boolean (n/a)]"
    ]
}
```

**Comment by adlmez** [comment]
We don't see any activity for a while.
Try using https://github.com/commerce-io/spring-boot-starter-data-search

**Comment by mlz11** [comment]
Hello @premkumarmcse 👋🏻 

I have just tested it out and it seems to work fine.

Could you please provide more information about the issue you encounter? I will close the issue until then.

<img width="932" alt="image" src="https://github.com/sipios/spring-search/assets/94069699/48c0d2a4-3b35-4808-abfc-d4e6bcdf2dbf">
