### ISSUE TITLE
Support For Instant

### ISSUE THREAD

**Issue by fernandoSkoda** [sipios/spring-search#56]
Hello

I would like to add InstantStrategy  and I would like to ask who is currently in charge of the project.
* Does anyone can help me to review my code once I made PR?
* What steps should I follow in order to add InstantStrategy functionality?

Thanks for your time

**Comment by fernandoSkoda** [comment]
UPDATE:
Made PR https://github.com/sipios/spring-search/pull/57

**Comment by millerdx** [comment]
This issue can probably be closed as this PR was merged on 06 May 2022. 

While you're at it, how about releasing 0.2.5 ;)

**Comment by fernandoSkoda** [comment]
hi @millerdx how to trigger new release for 0.2.5?

**Comment by millerdx** [comment]
> hi @millerdx how to trigger new release for 0.2.5?

@fernandoSkoda We can't. I'm guessing there hasn't been a release in such a long time because nobody that's still around has creds to the ossrh account.

**Comment by fernandoSkoda** [comment]
@millerdx Thats sad because I have a ton of changes I would like to merge 😅

**Comment by mlz11** [comment]
Hi @fernandoSkoda @millerdx 👋🏻 

We are in the process of releasing 0.2.5 (waiting for permissions) and then we will release 0.3.0 if all goes well.

I'm closing this issue.

**Comment by mlz11** [comment]
[spring-search-0.2.5](https://github.com/sipios/spring-search/releases/tag/spring-search-0.2.5)
