### ISSUE TITLE
Query with boolean parameters

### ISSUE THREAD

**Issue by NH0** [sipios/spring-search#6]
For the moment with a model of the kind : 

```kotlin
@Entity
@Table(name="USERS")
data class Users(
        @Id
        @GeneratedValue(strategy = GenerationType.AUTO)
        var userId: Long? = null,

        @Column(name = "isAdmin")
        var isAdmin: Boolean = false,
) { }
```

The following query will not work : `?search=isAdmin:false`

Any query with the `isAdmin` parameter will not work as Boolean types isn't supported yet.

**Comment by MollardMichael** [comment]
I've got a proposal for Boolean parameters and other (date as an example).

You can check it out here -> https://github.com/sipios/spring-search/pull/10

**Comment by luc-boussant** [comment]
The Pull request has been merged :)
