### ISSUE TITLE
Upgrade Spring Version 3.0.2 ( jakarta.persistence, antlr4)

### ISSUE THREAD

**Issue by LeandriT** [sipios/spring-search#62]
Actually the version of spring boot recent delivered is 3.0.2 and in this version we use jakarta.persistence and spring search (version 0.2.2) is not supporting this upgrade..  my question: Is this migration planned? to upgrade to the most recent spring boot version as of (02-13-2023) 3.0.2 that works with jakarta.persistence, and antlr4  (Jakarte EE 10) (Spring Framework 6.0) ?

**Comment by LeandriT** [comment]
<img width="1696" alt="Captura de pantalla 2023-02-13 a la(s) 15 13 28" src="https://user-images.githubusercontent.com/6405810/218565112-5646837f-88da-48b7-9b74-ac93d9135ee1.png">

**Comment by torshid** [comment]
Looks like this repo isn't maintained anymore, you may check our solid alternative here https://github.com/turkraft/springfilter.
It supports filtering collections, enums, all date types and much more. You can even use functions, and customize the query language with your own operators.

**Comment by dorian-frances** [comment]
We are currently in the process of migrating to Spring 3. We'll let you all know when it's done.
