### ISSUE TITLE
Support character escaping in queries

### ISSUE THREAD

**Issue by NH0** [sipios/spring-search#7]
With a value beginning with `*`, it is impossible to query with a STARTS_WITH operation.

For example : 
```kotlin
@Column(name = "isAdmin")
var username: String = "*MVP_07",
) { }
```
The following queries will NOT give all the usernames starting with `*` :  
```
?search=username:**
?search=username:\**
?search=username:'*'*
?search=username:'**'
?search=username:'\*'*
```

For the moment, avoid values starting with `*`.

It is also not possible to make a query with the character `&` inside it, even if it is enclosed in quotes.

**Comment by luc-boussant** [comment]
Hello,

Indeed, this is one of the features that will need to be implemented in the future.
It is added to the roadmap of the project.
However, if you want to work on it you can create an MR with the changes :)
I will be happy to review it when I can.
