### ISSUE TITLE
Not Allowing _ inside the key of a search spec

### ISSUE THREAD

**Issue by yashbalija1** [sipios/spring-search#85]
# Summary

{
        "novel_name_": "abc"
}

As per the above JSON, I am trying to search like  
?search=novel.novel_name_:null&size=2  and also ?search=novel.novel%5Fname%5F:null&size=2
but getting an error like nested exception is java.lang.NullPointerException: visit(ctx.query()) must not be null

@mlz11
Can you please help me out understanding this and how it can be achieved?

## Stacktrace

 "status": 500,
    "error": "Internal Server Error",
    "exception": "java.lang.NullPointerException",
    "message": "org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.NullPointerException: visit(ctx.query()) must not be null",

**Comment by phmz** [comment]
Hello @yashbalija1

Thank you for reporting this issue!
To help us understand and address the problem more effectively, we need a few additional details:

- **Spring Search and Java Version**:
  - What version of the Spring Search library are you using?
  - Could you also inform us about the Java version you're working with?

- **Entity Model and Reproduction Steps**:
  - Please provide details about the entity model involved in this query.
  - A minimal repository example or a detailed step-by-step description of how the issue occurs would be incredibly helpful for us to accurately reproduce and troubleshoot the problem.

**Comment by yashbalija1** [comment]
Hello @phmz 

Thanks for replying.

1. I am currently using the 0.2.4 version for spring search.
2. I am working with Java 8.

The entity model looks something like below.

`public class Entity{
    @Column(name = "books")
    @Convert(converter = JsonNodeConverter.class)
    private JsonNode books;
    @Column(name = "author")
    private String author;
}`

the book's column data that is stored in my db looks something like below.

{
  "book_name": "Into the future",
  "published_on":"2022-12-12",
}

Now I am trying to do a search spec on the above entity.

?search=books.book_name!null OR ?search=books.book_name:null

**Comment by phmz** [comment]
Hello @yashbalija1,

After reviewing your issue, the feature you're asking about is not supported in our project at this time. If you're interested and able to contribute this functionality, we would greatly appreciate a pull request.
